config/routes.rb
Rails.application.routes.draw do
  scope module: :front do
    root 'home#show'

    resources :characters

    namespace :api do
      get 'characters_search', action: :search, controller: :characters
    end
  end

  namespace :admin do
    root 'home#show'

    resources :users do
      patch :block, on: :member
      patch :unblock, on: :member
      get :invite_code, on: :collection
    end

    resources :characters, except: [:show]
    namespace :pages do
      resource :front_page, except: [:index, :new, :create, :destroy], path: :front
    end
  end

  get :login, to: 'sessions#new'
  match '/auth/:provider/callback', to: 'sessions#create', as: :login_callback, via: [:get, :post]
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
end

app/models/character.rb
# frozen_string_literal: true

class Character < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :left_character_relationships, -> { right_visible },
           class_name: 'CharacterRelationship',
           foreign_key: :character_left_id,
           inverse_of: :character_left,
           dependent: :destroy
  has_many :right_character_relationships, -> { left_visible },
           class_name: 'CharacterRelationship',
           foreign_key: :character_right_id,
           inverse_of: :character_right,
           dependent: :destroy

  accepts_nested_attributes_for :left_character_relationships,
                                :right_character_relationships,
                                allow_destroy: true

  validates :author, :name, :species, :role, presence: true

  scope :default_order, -> { order(:name) }
  scope :estate_characters, -> { where(athenaeum_character: false) }
  scope :visible, -> { where('NOT hidden') }

  def self.visible_for(user)
    visible.or(where(author: user))
  end

  before_save :capitalize_indexable_fields

  def author_name
    author&.display_name
  end

  def relationships
    left = left_character_relationships.includes(:character_right).map do |rel|
      [rel.label_right, rel.character_right]
    end

    right = right_character_relationships.includes(:character_left).map do |rel|
      [rel.label_left, rel.character_left]
    end

    (left + right).sort_by(&:first)
  end

  private

  def capitalize_indexable_fields
    self.species = species.mb_chars.tap { |c| c[0] = c[0].upcase }.to_s
    self.role = role.mb_chars.tap { |c| c[0] = c[0].upcase }.to_s
  end
end

app/controllers/admin/characters_controller.rb
module Admin
  class CharactersController < BaseController
    include WithSorting

    SORT_COLUMNS = {
      id: :_self,
      athenaeum_character: :_self,
      author_name: 'users.display_name',
      name: :_self,
      species: :_self,
      role: :_self
    }

    def index
      @characters = Character.includes(:author)
                             .references(:author)
                             .order(custom_order)
                             .page(params[:page])
                             .per(20)
    end

    def edit
      @character = find_character
    end

    def new
      @character = build_character
    end

    def create
      @character = build_character
      save_character || render(:new)
    end

    def update
      @character = find_character
      save_character || render(:edit)
    end

    def destroy
      @character = find_character
      @character.destroy
      redirect_to admin_characters_path, notice: 'Character deleted'
    end

    private

    def find_character
      Character.find(params[:id])
    end

    def build_character
      Character.new(author: current_user)
    end

    def save_character
      if @character.update(character_params)
        redirect_to admin_characters_path, notice: t('.success')
      end
    end

    def character_params
      params.require(:character).permit(:name, :species, :bio, :role,
                                        :author_id, :athenaeum_character,
                                        :hidden, :picture_url, :picture_source_url)
    end
  end
end

app/controllers/front/api/characters_controller.rb
module Front
  module Api
    class CharactersController < ApplicationController
      def search
        @use_case = CharactersSearch.call(user: current_user,
                                          search: params[:search])
        render json: @use_case.collection
      end
    end
  end
end

app/controllers/front/base_controller.rb
module Front
  class BaseController < ApplicationController
    layout 'front'
  end
end

app/controllers/front/characters_controller.rb
module Front
  class CharactersController < BaseController
    helper_method :search_params

    def index
      authorize Character
      @search_form = CharactersSearchForm.new(search_params)
      result = CharactersIndex.(user: current_user, search_form: @search_form, page: params[:page])
      @characters = result.collection
      @authors = User.joins(:characters).order(:display_name).distinct
    end

    def show
      @character = find_character
      fresh_when @character
    end

    def new
      @character = build_character
      authorize @character
    end

    def create
      @character = build_character
      authorize @character
      save_character || render(:new)
    end

    def edit
      @character = find_character
    end

    def update
      @character = find_character
      save_character || render(:edit)
    end

    def destroy
      @character = find_character
      @character.destroy
      redirect_to characters_path, notice: 'Character deleted'
    end

    private

    def find_character
      Character.visible_for(current_user)
               .find(params[:id])
               .tap { |ch| authorize(ch) }
    end

    def build_character
      Character.new(author: current_user)
    end

    def save_character
      @character.assign_attributes(character_params)
      if @character.save
        redirect_to character_path(@character), notice: t('.success')
      else
        Rails.logger.debug @character.errors.full_messages
        false
      end
    end

    def character_params
      params.require(:character)
            .permit(:name, :species, :bio, :role,
                    :athenaeum_character, :hidden,
                    :picture_url, :picture_source_url,
                    left_character_relationships_attributes: [
                      :_destroy, :id, :character_right_id,
                      :label_left, :label_right
                    ],
                    right_character_relationships_attributes: [
                      :_destroy, :id, :character_left_id,
                      :label_left, :label_right
                    ]
                   )
    end

    def search_params
      return {} unless params[:q]

      params[:q].permit(:search, :author_id)
    end

    def title
      case action_name
      when 'index' then "#{super} — characters list"
      when 'new', 'create' then "#{super} — new character"
      when 'edit', 'update' then "#{super} — editing character #{@character.name}"
      else super
      end
    end
  end
end

app/controllers/front/home_controller.rb
module Front
  class HomeController < BaseController
    skip_before_action :ensure_login

    def show
      # TODO: move to a container
      @front_page = Pages::FrontPage.first
      fresh_when [current_user, @front_page] unless Rails.env.development?
    end
  end
end

app/helpers/front/characters_helper.rb
# frozen_string_literals: true

module Front::CharactersHelper
  def characters_group_vals
    content = @characters.keys.map(&method(:characters_group_item))
    content_tag(:ul, content.join("\n").html_safe)
  end

  def characters_group_item(group_val)
    content_tag(:a, group_val.title, href: "##{group_val.key}", class: 'button is-text')
  end

  def character_relationship_delete_btn(object)
    action = object.persisted? ? :disable : :destroy
    button_tag 'Delete', type: :button,
               class: 'button is-danger is-fullwidth',
               data: { action: "character-relationships-form##{action}" }
  end
end

app/views/front/characters/_base_form.html.erb
<% if policy(f.object).set_athenaeum? %>
    <div class="field">
        <div class="control">
            <%= f.label :athenaeum_character, class: 'checkbox' do %>
                <%= f.check_box :athenaeum_character %>
                <span>Is an athenaeum character?</span>
            <% end %>
        </div>
    </div>
<% end %>

<div class="field">
    <div class="control">
        <%= f.label :hidden, class: 'checkbox' do %>
            <%= f.check_box :hidden %>
            <span>Hide the character? Only you will be able to see it</span>
        <% end %>
    </div>
</div>

<div class="field">
    <%= f.label :name, class: 'label' %>
    <div class="control">
        <%= f.text_field :name, class: 'input', required: true %>
    </div>
</div>

<div class="box">
    <div class="field">
        <%= f.label :picture_url %>
        <div class="control">
            <%= f.text_field :picture_url, class: 'input' %>
        </div>
    </div>
    <p>
        <strong>Hey! If you have a source for that character pic, please do link it here!</strong>
    </p>
    <div class="field">
        <%= f.label :picture_source_url %>
        <div class="control">
            <%= f.text_field :picture_source_url, class: 'input' %>
        </div>
    </div>
</div>

<div class="field">
    <%= f.label :species %>
    <div class="control">
        <%= f.text_field :species, class: 'input', required: true %>
    </div>
</div>

<div class="field">
    <%= f.label :role %>
    <div class="control">
        <%= f.text_field :role, class: 'input', required: true %>
    </div>
</div>

<div class="field">
    <%= f.label :bio %>
    <div class="control">
        <%= f.text_area :bio, rows: 20, class: 'textarea' %>
    </div>
    <p><%== Settings.forms.hints.markdown %></p>
</div>

app/views/front/characters/_form.html.erb
<%= form_for @character do |f| %>
    <div class="tabs">
        <ul>
            <li><a href="#base_form">Base info</a></li>
            <li><a href="#relationships_form">Relationships</a></li>
        </ul>
    </div>

    <section id="base_form">
        <%= render partial: "base_form", locals: { f: f } %>
    </section>
    <section id="relationships_form" class="field character-relationships-form" data-controller="character-relationships-form">
        <div class="level is-mobile">
            <div class="level-left">
                <h2 class="title level-item is-3">Relationships (β)</h2>
            </div>
        </div>
        <div class="character-relationships-form__container" data-target="character-relationships-form.container">
            <%= render partial: "relationships_form", locals: { f: f } %>
        </div>
    </section>

    <div class="field">
        <div class="control">
            <%= f.submit class: 'button is-success' %>
        </div>
    </div>
<% end %>

app/views/front/characters/_groupers.html.erb
<div class="tabs">
    <ul>
        <% CharactersIndex::GROUPERS.each do |name, grouper| %>
            <li class="<%= 'is-active' if grouper.name == @grouper %>">
                <%= link_to name.capitalize, { group_by: name, new_design: params[:new_design] } %>
            </li>
        <% end %>
    </ul>
</div>

<div class="character-index-goto-list">
    <span class="has-text-weight-bold is-inline-block character-index-goto-list__title">Go to:</span>
    <div class="buttons character-index-goto-list__buttons">
        <% @characters.keys.each do |group_val| %>
            <%= characters_group_item(group_val) %>
        <% end %>
    </div>
</div>

app/views/front/characters/_index_group.html.erb
<section class="box" id="<%= title.key %>">
    <header class="character-index__header">
        <h2 class="is-size-4 has-text-weight-bold"><%= title %></h2>
        <a href="#" class="top-link">To top</a>
    </header>
    <ul class="character-index__container">
        <%= render partial: 'index_item', collection: characters, as: :character %>
    </ul>
</section>

app/views/front/characters/_index_item.html.erb
<% cache [character, character.token_flags.join(','), character.actions.join(',')] do %>
    <%= content_tag :li, class: character.item_classes do %>
        <header class="character-index-item__header">
            <span class="character-index-item__title">
                <%= link_to character.name, character_path(character) %>
                <span>by&nbsp;<%= character.author.display_name %></span>
            </span>

            <%== character.tokens %>
        </header>
        <figure class="character-index-item__img-container image">
            <%= character.character_image_link %>
        </figure>
        <div class="character-index-item__content">
            <div class="character-index-item__description">
                <span><%= character.species %></span>
                <span><%= character.role %></span>
            </div>
        </div>
        <% if character.actions.present? %>
            <footer>
                <% character.actions.each do |action| %>
                    <%= character.links[action] %>
                <% end %>
            </footer>
        <% end %>
    <% end %>
<% end %>

app/views/front/characters/_relationships_form.html.erb
<%= f.fields_for :left_character_relationships do |ff| %>
    <%= render partial: "relationships_subform", locals: { ff: ff, mode: :left } %>
<% end %>

<%= f.fields_for :right_character_relationships do |ff| %>
    <%= render partial: "relationships_subform", locals: { ff: ff, mode: :right } %>
<% end %>

<%= button_tag 'Add relationship', type: :button, class: 'button is-primary character-relationships-form__add-rel-btn', data: { target: 'character-relationships-form.addButton', action: 'character-relationships-form#addRelationship' } %>

<template data-target="character-relationships-form.relationshipTemplate">
    <%= f.fields_for :left_character_relationships, @character.left_character_relationships.new do |ff| %>
        <%= render partial: 'relationships_subform', locals: { ff: ff, mode: :left } %>
    <% end %>
</template>

<div class="modal" tabindex="-1" role="dialog" id="character_select_modal" data-controller="character-relationships-modal" data-action="keydown->character-relationships-modal#close changecharacter->character-relationships-modal#open" data-search-url="<%= api_characters_search_path %>">
    <div class="modal-background"></div>
    <button type="button" class="modal-close is-large" data-dismiss="modal" aria-label="Close" data-action="click->character-relationships-modal#close">
        <span aria-hidden="true">&times;</span>
    </button>
    <div class="modal-content">
        <div class="modal-body">
            <div class="box">
                <div class="field">
                    <label for="character_name_prefix"></label>
                    <div class="control">
                        <input class="input" data-target="character-relationships-modal.prefixInput" data-action="input->character-relationships-modal#searchPrefix" id="character_name_prefix" type="text" name="character_name_prefix" />
                    </div>
                </div>
                <div data-target="character-relationships-modal.minPrefixDisplay">
                    Enter at least <span data-target="character-relationships-modal.minPrefixSpan">3</span> characters to display the list
                </div>
                <div class="has-text-centered is-hidden" data-target="character-relationships-modal.displaySpinner">
                    <div class="spinner"></div>
                </div>
                <div class="panel is-hidden" data-target="character-relationships-modal.resultsPanel">
                </div>
            </div>
        </div>
    </div>
</div>

app/views/front/characters/_relationships_subform.html.erb
<% other_mode = mode == :left ? :right : :left %>

<div class="is-hidden relationship-subform__idx"><%= ff.index %></div>
<% if ff.object.persisted? %>
    <%= ff.hidden_field :id %>
    <%= ff.hidden_field :_destroy %>
<% end %>

<div class="field relationship-subform__rel1">
    <div class="control">
        <%= ff.text_field :"label_#{mode}", class: :input, required: true %>
    </div>
</div>
<div class="has-text-centered relationship-subform__of">of</div>
<div class="field is-grouped relationship-subform__character">
    <div class="control is-expanded" data-controller="character-relationships-character" data-character-name="<%= ff.object.send("character_#{other_mode}")&.name %>">
        <%= ff.text_field :"character_#{other_mode}_id", class: :input, data: { target: 'character-relationships-character.input' } %>
    </div>
</div>
<div class="field relationship-subform__rel2">
    <div class="control has-icons-left has-icons-right">
        <%= ff.text_field :"label_#{other_mode}", class: :input, required: true %>
        <span class="icon is-small is-left">(</span>
        <span class="icon is-small is-right">)</span>
    </div>
</div>
<div class="relationship-subform__delete-btn">
    <%= character_relationship_delete_btn(ff.object) %>
</div>

<hr class="is-hidden-tablet relationship-subform__hr" />

app/views/front/characters/_search_form.html.erb
<%= form_for @search_form, url: { action: :index }, method: :get, as: :q do |f| %>
    <%= f.hidden_field :author_id %>
    <div class="columns is-mobile">
        <div class="field column">
            <div class="control">
                <%= f.text_field :search, placeholder: 'Search by character name', class: 'input' %>
            </div>
        </div>

        <div class="field column buttons is-narrow">
            <%= link_to 'Reset', { action: :index, q: nil }, class: 'button is-warning' %>
            <%= f.submit 'Search', class: 'button is-info' %>
        </div>
    </div>
<% end %>

<div class="columns">
    <div class="column is-narrow">
        <span class="subtitle is-5">Filter by author</span>
    </div>
    <div class="column">
        <div class="buttons">
            <%= link_to 'All', { action: :index, q: search_params.except(:author_id) }, class: 'button is-warning' %>
            <% @authors.each do |author| %>
                <%= link_to author.display_name, { action: :index, q: search_params.merge(author_id: author.id) }, class: ['button', 'is-info', ('is-outlined' unless @search_form.author_id == author.id)].compact %>
            <% end %>
        </div>
    </div>
</div>

app/views/front/characters/edit.html.erb
<header class="header">
    <h1 class="title">Edit character</h1>
</header>

<%= render 'form' %>

app/views/front/characters/index.html.erb
<header class="header">
    <h1 class="title">Characters list</h1>
    <div class="field">
        <%= link_to 'New character', new_character_path, class: 'button is-success' %>
    </div>
    <div>
        <%= render 'search_form' %>
    </div>
</header>

<% if @characters.present? %>
    <section class="section characters-index">
        <%= paginate @characters.object, views_prefix: 'front' %>

        <ul class="character-index__container">
            <%= render partial: 'index_item', collection: @characters, as: :character %>
        </ul>

        <%= paginate @characters.object, views_prefix: 'front' %>
    </section>
<% else %>
    <p class="subtitle is-5 has-text-centered">Sorry, no characters found</p>
<% end %>

app/views/front/characters/new.html.erb
<header class="header">
    <h1 class="title">Create new character</h1>
</header>

<%= render 'form' %>

app/views/front/characters/show.html.erb
<article class="character-show is-clearfix">
    <header class="header">
        <h1 class="title">
            <%= @character.name %>
            <small>by <%= @character.author.display_name %></small>
        </h1>
        <h2 class="has-text-grey"><%= @character.species %> • <%= @character.role %></h2>
    </header>
    <% if @character.picture_url.present? %>
        <figure class="image is-pulled-left character-show__pic">
            <a href="<%= @character.picture_url %>">
                <img src="<%= @character.picture_url %>"/>
            </a>
            <% if @character.picture_source_url.present? %>
                <figcaption class="has-background-light is-inline-block"><a href="<%= @character.picture_source_url %>">Source</a></figcaption>
            <% end %>
        </figure>
    <% end %>

    <div class="content character-show__bio">
        <%# TODO: think of better cache key %>
        <% cache [@character, :bio] do %>
            <%= UserText.process_md(@character.bio) %>
        <% end %>

        <ul>
            <% @character.relationships.each do |label, char| %>
                <li>
                    <span><%= label.capitalize %>:&nbsp;</span><%= link_to char.name, character_path(char) %>
                </li>
            <% end %>
        </ul>
    </div>
    <% if policy(@character).edit? %>
        <%= link_to edit_character_path(@character), class: 'button is-link' do %>
            <%= octicon(:pencil) %>
            <span>&nbsp;Edit</span>
        <% end %>
    <% end %>
    <% if policy(@character).destroy? %>
        <%= link_to character_path(@character), method: :delete, class: 'button is-danger', data: {confirm: 'Are you sure you want to delete this character?'} do %>
            <%= octicon(:trashcan) %>
            <span>&nbsp;Delete</span>
        <% end %>
    <% end %>
</article>