config/routes.rb
Rails.application.routes.draw do
  scope module: :front do
    root 'home#show'

    resources :characters

    namespace :api do
      get 'characters_search', action: :search, controller: :characters
    end
  end

  namespace :admin do
    root 'home#show'

    resources :users do
      patch :block, on: :member
      patch :unblock, on: :member
      get :invite_code, on: :collection
    end

    resources :characters, except: [:show]
    namespace :pages do
      resource :front_page, except: [:index, :new, :create, :destroy], path: :front
    end
  end

  get :login, to: 'sessions#new'
  match '/auth/:provider/callback', to: 'sessions#create', as: :login_callback, via: [:get, :post]
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
end

app/models/character.rb
# frozen_string_literal: true

class Character < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :left_character_relationships, -> { right_visible },
           class_name: 'CharacterRelationship',
           foreign_key: :character_left_id,
           inverse_of: :character_left,
           dependent: :destroy
  has_many :right_character_relationships, -> { left_visible },
           class_name: 'CharacterRelationship',
           foreign_key: :character_right_id,
           inverse_of: :character_right,
           dependent: :destroy

  accepts_nested_attributes_for :left_character_relationships,
                                :right_character_relationships,
                                allow_destroy: true

  validates :author, :name, :species, :role, presence: true

  scope :default_order, -> { order(:name) }
  scope :estate_characters, -> { where(athenaeum_character: false) }
  scope :visible, -> { where('NOT hidden') }

  def self.visible_for(user)
    visible.or(where(author: user))
  end

  before_save :capitalize_indexable_fields

  def author_name
    author&.display_name
  end

  def relationships
    left = left_character_relationships.includes(:character_right).map do |rel|
      [rel.label_right, rel.character_right]
    end

    right = right_character_relationships.includes(:character_left).map do |rel|
      [rel.label_left, rel.character_left]
    end

    (left + right).sort_by(&:first)
  end

  private

  def capitalize_indexable_fields
    self.species = species.mb_chars.tap { |c| c[0] = c[0].upcase }.to_s
    self.role = role.mb_chars.tap { |c| c[0] = c[0].upcase }.to_s
  end
end

app/controllers/admin/characters_controller.rb
module Admin
  class CharactersController < BaseController
    include WithSorting

    SORT_COLUMNS = {
      id: :_self,
      athenaeum_character: :_self,
      author_name: 'users.display_name',
      name: :_self,
      species: :_self,
      role: :_self
    }

    def index
      @characters = Character.includes(:author)
                             .references(:author)
                             .order(custom_order)
                             .page(params[:page])
                             .per(20)
    end

    def edit
      @character = find_character
    end

    def new
      @character = build_character
    end

    def create
      @character = build_character
      save_character || render(:new)
    end

    def update
      @character = find_character
      save_character || render(:edit)
    end

    def destroy
      @character = find_character
      @character.destroy
      redirect_to admin_characters_path, notice: 'Character deleted'
    end

    private

    def find_character
      Character.find(params[:id])
    end

    def build_character
      Character.new(author: current_user)
    end

    def save_character
      if @character.update(character_params)
        redirect_to admin_characters_path, notice: t('.success')
      end
    end

    def character_params
      params.require(:character).permit(:name, :species, :bio, :role,
                                        :author_id, :athenaeum_character,
                                        :hidden, :picture_url, :picture_source_url)
    end
  end
end

app/controllers/front/api/characters_controller.rb
module Front
  module Api
    class CharactersController < ApplicationController
      def search
        @use_case = CharactersSearch.call(user: current_user,
                                          search: params[:search])
        render json: @use_case.collection
      end
    end
  end
end

app/controllers/front/characters_controller.rb
module Front
  class CharactersController < BaseController
    helper_method :search_params

    def index
      authorize Character
      @search_form = CharactersSearchForm.new(search_params)
      result = CharactersIndex.(user: current_user, search_form: @search_form, page: params[:page])
      @characters = result.collection
      @authors = User.joins(:characters).order(:display_name).distinct
    end

    def show
      @character = find_character
      fresh_when @character
    end

    def new
      @character = build_character
      authorize @character
    end

    def create
      @character = build_character
      authorize @character
      save_character || render(:new)
    end

    def edit
      @character = find_character
    end

    def update
      @character = find_character
      save_character || render(:edit)
    end

    def destroy
      @character = find_character
      @character.destroy
      redirect_to characters_path, notice: 'Character deleted'
    end

    private

    def find_character
      Character.visible_for(current_user)
               .find(params[:id])
               .tap { |ch| authorize(ch) }
    end

    def build_character
      Character.new(author: current_user)
    end

    def save_character
      @character.assign_attributes(character_params)
      if @character.save
        redirect_to character_path(@character), notice: t('.success')
      else
        Rails.logger.debug @character.errors.full_messages
        false
      end
    end

    def character_params
      params.require(:character)
            .permit(:name, :species, :bio, :role,
                    :athenaeum_character, :hidden,
                    :picture_url, :picture_source_url,
                    left_character_relationships_attributes: [
                      :_destroy, :id, :character_right_id,
                      :label_left, :label_right
                    ],
                    right_character_relationships_attributes: [
                      :_destroy, :id, :character_left_id,
                      :label_left, :label_right
                    ]
                   )
    end

    def search_params
      return {} unless params[:q]

      params[:q].permit(:search, :author_id)
    end

    def title
      case action_name
      when 'index' then "#{super} — characters list"
      when 'new', 'create' then "#{super} — new character"
      when 'edit', 'update' then "#{super} — editing character #{@character.name}"
      else super
      end
    end
  end
end

app/helpers/front/characters_helper.rb
# frozen_string_literals: true

module Front::CharactersHelper
  def characters_group_vals
    content = @characters.keys.map(&method(:characters_group_item))
    content_tag(:ul, content.join("\n").html_safe)
  end

  def characters_group_item(group_val)
    content_tag(:a, group_val.title, href: "##{group_val.key}", class: 'button is-text')
  end

  def character_relationship_delete_btn(object)
    action = object.persisted? ? :disable : :destroy
    button_tag 'Delete', type: :button,
               class: 'button is-danger is-fullwidth',
               data: { action: "character-relationships-form##{action}" }
  end
end

app/views/admin/characters/_character.html.erb
<tr>
    <td><%= character.id %></td>
    <td>
        <%# TODO: extract into helpers %>
        <% if character.athenaeum_character? %>
            <abbr title="Athenaeum character">A</abbr>
        <% end %>

        <% if character.hidden? %>
            <abbr title="Hidden"><%= octicon('eye-closed') %></abbr>
        <% end %>
    </td>
    <td>
        <%= link_to character_path(character), target: '_blank' do %>
            <%= octicon(:link) %>
        <% end %>
    </td>
    <td><%= character.author_name %></td>
    <td><%= character.name %></td>
    <td><%= character.species %></td>
    <td><%= character.role %></td>
    <td><%= I18n.l character.created_at, format: :short %></td>
    <td class="actions-cell">
        <%= edit_link(edit_admin_character_path(character)) %>&nbsp;
        <%= delete_link(admin_character_path(character), class: '') %>
    </td>
</tr>

app/views/admin/characters/_form.html.erb
<div class="row">
    <div class="col-sm-12">
        <%= bootstrap_form_for @character, url: url do |f| %>
            <div class="form-check">
                <%= f.label :athenaeum_character, class: 'form-check-label' do %>
                    <%= f.check_box :athenaeum_character %>
                    <span>Is an athenaeum character?</span>
                <% end %>
            </div>
            <div class="form-check">
                <%= f.label :hidden, class: 'form-check-label' do %>
                    <%= f.check_box :hidden %>
                    <span>Is hidden?</span>
                <% end %>
            </div>
            <%= f.select :author_id, User.order(:display_name).map { |u| [u.display_name, u.id] } %>
            <%= f.text_field :name %>
            <%= f.text_field :picture_url %>
            <%= f.text_field :picture_source_url %>
            <%= f.text_field :species %>
            <%= f.text_field :role %>
            <%= f.text_area :bio, rows: 20, hint_html: Settings.forms.hints.markdown %>
            <%= f.submit type: :primary %>
        <% end %>
    </div>
</div>

app/views/admin/characters/edit.html.erb
<header class="row">
    <div class="col-sm-12">
        <h1>Edit character</h1>
    </div>
</header>

<%= render 'form', url: admin_character_path(@character) %>

app/views/admin/characters/index.html.erb
<div class="row pb-2">
    <div class="col-sm-12">
        <%= link_to 'New character', new_admin_character_path, class: 'btn btn-success' %>
    </div>
</div>

<%= admin_paginator @characters %>

<div class="row">
    <div class="col-sm-12">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th></th>
                    <th>Link</th>
                    <th><%= sort_link 'Author', :author_name %></th>
                    <th><%= sort_link 'Name', :name %></th>
                    <th><%= sort_link 'Species', :species %></th>
                    <th><%= sort_link 'Role', :role %></th>
                    <th><%= sort_link 'Created at', :created_at %></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <%= render @characters %>
            </tbody>
        </table>
    </div>
</div>

app/views/admin/characters/new.html.erb
<header class="row">
    <div class="col-sm-12">
        <h1>Create new character</h1>
    </div>
</header>

<%= render 'form', url: admin_characters_path %>