config/routes.rb
Rails.application.routes.draw do
  scope module: :front do
    root 'home#show'

    resources :characters

    namespace :api do
      get 'characters_search', action: :search, controller: :characters
    end
  end

  namespace :admin do
    root 'home#show'

    resources :users do
      patch :block, on: :member
      patch :unblock, on: :member
      get :invite_code, on: :collection
    end

    resources :characters, except: [:show]
    namespace :pages do
      resource :front_page, except: [:index, :new, :create, :destroy], path: :front
    end
  end

  get :login, to: 'sessions#new'
  match '/auth/:provider/callback', to: 'sessions#create', as: :login_callback, via: [:get, :post]
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize

  has_many :characters, inverse_of: :author, foreign_key: :author_id

  validates :display_name, presence: true
  validates :invite_code, uniqueness: true,
            if: proc { |user| user.invite_code.present? }
  validates :uid, uniqueness: true, if: proc { |user| user.uid.present? }

  scope :unblocked, -> { where(blocked: false) }

  enumerize :user_type, in: %i[estate_user advanced_user admin],
            default: :estate_user
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  include WithSorting

  SORT_COLUMNS = {
    id: :_self,
    display_name: :_self,
    last_login: :_self,
    blocked: :_self
  }.freeze

  def index
    @users = User.order(custom_order)
                 .page(params[:page])
                 .per(20)
  end

  def show
    @user = Admin::UserDecorator.decorate find_user
  end

  def new
    @user = User.new
  end

  def edit
    @user = find_user
  end

  def update
    @user = find_user
    if @user.update(user_params)
      redirect_to admin_users_path, notice: 'User updated successfully'
    else
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'User created successfully'
    else
      render :new
    end
  end

  def destroy
    @user = find_user
    @user.destroy
    redirect_to admin_users_path, notice: 'User deleted'
  end

  def block
    @user = find_user
    @user.update(blocked: true)
    redirect_to admin_users_path, notice: 'User blocked'
  end

  def unblock
    @user = find_user
    @user.update(blocked: false)
    redirect_to admin_users_path, notice: 'User unblocked'
  end

  def invite_code
    so = User::GenerateInviteCode.new
    render json: { invite_code: so.call }
  end

  private

  def find_user
    User.find(params[:id])
  end

  def user_params
    params.require(:user)
          .permit(:display_name, :user_type, :invite_code, :blocked)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def invite_code_button(user)
    return if user.invite_code.blank?

    button_tag(type: :button, 
               class: 'btn btn-secondary btn-sm invite-link', data: {
                 invite_url: invite_url(user.invite_code),
                 user_name: user.display_name,
                 action: 'user-invite-links#openModal'
               }) { octicon(:info, height: 24) }
  end
end

app/views/admin/users/_form.html.erb
<%= bootstrap_form_for @user, url: url, data: { controller: 'user-form' } do |f| %>
    <%= f.text_field :display_name %>
    <%= f.select :user_type, enumerize_select_options(User.user_type) %>
    <div class="row">
        <div class="col-md-8 col-lg-4">
            <%= f.text_field :invite_code, data: { target: 'user-form.inviteCodeInput' } %>
        </div>
        <div class="col-md-3 col-lg-2">
            <%= label_tag 'generate', '&nbsp;'.html_safe %>
            <div>
                <%= link_to 'Generate', invite_code_admin_users_path, class: 'btn btn-info', id: 'generate_invite_code', 'data-action': 'user-form#generateInviteCode' %>
            </div>
        </div>
    </div>
    <div class="form-check">
        <%= f.label :blocked, class: 'form-check-label' do %>
            <%= f.check_box :blocked %>
            Block user
        <% end %>
    </div>
    <div>
        <%= f.submit class: 'btn btn-success' %>
    </div>
<% end %>

app/views/admin/users/edit.html.erb
<%= render 'form', url: admin_user_path(@user) %>

app/views/admin/users/index.html.erb
<div class="row mb-2">
    <div class="col-sm-12">
        <%= link_to 'Add user', new_admin_user_path, class: 'btn btn-success' %>
    </div>
</div>

<%= admin_paginator(@users) %>

<div class="row" data-controller="user-invite-links">
    <div class="col-sm-12">
        <table class="table">
            <thead>
                <tr>
                    <th><%= sort_link '#', :id %></th>
                    <th><%= sort_link 'Display name', :display_name %></th>
                    <th class="d-none d-md-table-cell">User type</th>
                    <th class="d-none d-md-table-cell"><%= sort_link 'Last login time', :last_login %></th>
                    <th class="d-none d-md-table-cell">Invite link</th>
                    <th class="d-none d-md-table-cell"><%= sort_link 'Is blocked', :blocked %></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                    <tr>
                        <td><%= user.id %></td>
                        <td><%= link_to user.display_name, admin_user_path(user) %></td>
                        <td class="d-none d-md-table-cell"><%= user.user_type_text %></td>
                        <td class="d-none d-md-table-cell"><%= user.last_login ? I18n.l(user.last_login, format: :short) : '—' %></td>
                        <td class="d-none d-md-table-cell">
                            <%= invite_code_button(user) %>
                        </td>
                        <td class="d-none d-md-table-cell"><%= user.blocked? ? 'BLOCKED' : 'Active' %></td>
                        <td class="actions-cell">
                            <%= edit_link({ action: :edit, id: user.id }) %>&nbsp;
                            <%= delete_link({ action: :destroy, id: user.id }, class: '') %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

    <div class="modal" tabindex="-1" role="dialog" data-target="user-invite-links.modal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" data-target="user-invite-links.modalTitle"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" data-target="user-invite-links.modalBody">
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/users/new.html.erb
<%= render 'form', url: admin_users_path %>

app/views/admin/users/show.html.erb
<h1>
    User profile #<%= @user.id %>
    <% if @user.blocked? %>
        <small class="text-danger">BLOCKED</small>
    <% end %>
</h1>

<table class="table user-show-table">
    <% @user.show_fields.each do |title, value| %>
        <tr>
            <th><%= title %></th>
            <td><%= value %></td>
        </tr>
    <% end %>
</table>