config/routes.rb
Rails.application.routes.draw do
  scope module: :front do
    root 'home#show'

    resources :characters

    namespace :api do
      get 'characters_search', action: :search, controller: :characters
    end
  end

  namespace :admin do
    root 'home#show'

    resources :users do
      patch :block, on: :member
      patch :unblock, on: :member
      get :invite_code, on: :collection
    end

    resources :characters, except: [:show]
    namespace :pages do
      resource :front_page, except: [:index, :new, :create, :destroy], path: :front
    end
  end

  get :login, to: 'sessions#new'
  match '/auth/:provider/callback', to: 'sessions#create', as: :login_callback, via: [:get, :post]
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= title %></title>
        <%= csrf_meta_tags %>

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <%= stylesheet_link_tag    'admin/application', media: 'all' %>
        <%= javascript_include_tag 'shared' %>
        <%= javascript_include_tag 'admin/application' %>

        <%= javascript_pack_tag 'admin' %>
    </head>

    <body>
        <%= content_for :navbar_left do %>
            <%= navbar_link('User interface', root_path, color: :info) %>
            <%= navbar_link('Users', admin_users_path) %>
            <%= navbar_link('Characters', admin_characters_path) %>
            <%= navbar_link('Front page', admin_pages_front_page_path) %>
        <% end %>

        <%= content_for :navbar_right do %>
            <%= navbar_text(current_user&.display_name) %>
            <%= navbar_link('Logout', logout_path, color: :danger, method: :delete) %>
        <% end %>

        <%= render 'shared/navbar/base', brand_title: Settings.strings.admin.brand_title, brand_path: admin_root_path, navbar_class: 'navbar-dark bg-dark' %>

        <main class="container mt-3">
            <%= render 'shared/flashes' %>
            <%= yield %>
        </main>

        <%= render 'shared/footer' %>
    </body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <%= stylesheet_link_tag    'front/application', media: 'all' %>
    <%= javascript_include_tag 'shared' %>
    <%= javascript_include_tag 'front/application' %>

    <%= stylesheet_pack_tag 'front' %>
    <%= javascript_pack_tag 'front' %>
  </head>

  <body>
      <%# TODO: extract into a helper/decorator? %>
      <% if current_user %>
          <% content_for :navbar_start do %>
              <%= link_to 'Characters', characters_path, class: 'navbar-item' %>
              <%= link_to 'New character', new_character_path, class: 'navbar-item' %>
          <% end %>

          <% content_for :navbar_end do %>
              <%- if current_user.user_type.admin? %>
                  <%= link_to'Admin interface', admin_root_path, class: 'navbar-item' %>
              <% end %>
              <span class="navbar-item has-text-primary"><%= current_user.display_name %></span>
              <%= link_to 'Logout', logout_path, class: 'navbar-item has-text-danger', data: { method: :delete } %>
          <% end %>
      <% else %>
          <% content_for :navbar_end do %>
              <%= link_to 'Login', login_path, class: 'navbar-item has-text-info' %>
          <% end %>
      <% end %>

      <%#= render 'shared/navbar/base', navbar_class: 'navbar-light bg-light', brand_title: Settings.strings.front.brand_title, brand_path: root_path %>

      <%= render 'shared/front/navbar', brand_title: Settings.strings.front.brand_title, brand_path: root_path %>

      <main>
          <div class="container">
              <%= render 'shared/front/flashes' %>

              <%= yield %>
          </div>
      </main>

      <footer class="footer">
          <div class="content has-text-centered">
              <%= render 'shared/footer_content' %>
              <p>Built with <a href="https://bulma.io/">Bulma</a></p>
          </div>
      </footer>
  </body>
</html>